CREATE DATABASE VENTAS
CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE VENTAS; 

CREATE TABLE HERRAMIENTA ( 
COD CHAR(6) NOT NULL PRIMARY KEY, 
DESCRIPCION VARCHAR(35) DEFAULT ' ', 
PRECIO DECIMAL(6,2) DEFAULT 0.0 
) ENGINE = InnoDB;
 
CREATE TABLE ALMACEN( 
COD CHAR(6) NOT NULL PRIMARY KEY, 
CINGRESO SMALLINT DEFAULT 0, 
CEGRESO SMALLINT DEFAULT 0,
CSALDO SMALLINT DEFAULT 0, 
FOREIGN KEY (COD) REFERENCES HERRAMIENTA(COD) 
) ENGINE = InnoDB; 


CREATE TABLE COMERCIAL ( 
NIT CHAR(11) NOT NULL PRIMARY KEY, 
NOMBRE VARCHAR(35) DEFAULT ' ', 
DIRECCION VARCHAR(30) DEFAULT ' ' 
) ENGINE = InnoDB; 

CREATE TABLE CLIENTE ( 
CI CHAR(11) NOT NULL PRIMARY KEY, 
NOMBRE VARCHAR(35) DEFAULT ' ', 
EDAD TINYINT UNSIGNED DEFAULT 0, 
SEXO CHAR(1), CHECK(SEXO IN('F', 'M')), 
TELEFONO INT DEFAULT 0 
) ENGINE = InnoDB; 

CREATE TABLE SOLICITUD ( 
NSOL SMALLINT NOT NULL PRIMARY KEY, 
FECHA DATETIME DEFAULT NOW(), 
CANTIDAD SMALLINT DEFAULT 0, 
CI CHAR(11), 
COD CHAR(6), 
STAT CHAR(1) DEFAULT ' ', 
FOREIGN KEY (CI) REFERENCES CLIENTE(CI),
FOREIGN KEY (COD) REFERENCES HERRAMIENTA(COD) 
) ENGINE = InnoDB; 


CREATE TABLE VENTA ( 
COD CHAR(6) NOT NULL, 
CI CHAR(11) NOT NULL, 
NSOL SMALLINT NOT NULL, 
CANTIDAD SMALLINT DEFAULT 0,
COSTO DECIMAL(6,2) DEFAULT 0.0, 
PRIMARY KEY(COD, CI, NSOL),
FOREIGN KEY (COD) REFERENCES HERRAMIENTA(COD),
FOREIGN KEY (CI) REFERENCES CLIENTE(CI),
FOREIGN KEY (NSOL) REFERENCES SOLICITUD(NSOL)
) ENGINE = InnoDB; 

CREATE TABLE COMPRA ( 
COD CHAR(6) NOT NULL, 
NIT CHAR(11) NOT NULL, 
CANTIDADC SMALLINT DEFAULT 0,
COSTOC DECIMAL(6,2) DEFAULT 0.0, 
PRIMARY KEY(COD, NIT),
FOREIGN KEY (COD) REFERENCES HERRAMIENTA(COD),
FOREIGN KEY (NIT) REFERENCES COMERCIAL(NIT)
) ENGINE = InnoDB; 

INSERT INTO HERRAMIENTA VALUES ('H-0001', 'ALICATE', 25);
INSERT INTO CLIENTE VALUES('1096745', 'CARLOS RUIZ', 24, 'M', 34567);
INSERT INTO COMERCIAL VALUES ('100000010', 'LIMPOR LTDA.', 'AV DEL MAESTRO # 650');
INSERT INTO ALMACEN VALUES ('H-0001', 100, 40, 60);
INSERT INTO SOLICITUD VALUES (2, NOW(), 5, '1096745', 'H-0001', ' ');
