/*
-------------------------------
-------- PRACTICO 9  ----------
-------------------------------*/

/*
8. TRANSACCION QUE REGISTRE UN SOLICITUD, REGISTRE LA VENTA RESPECTIVA Y ACTUALICE EL ALMACEN.
LOS DATOS SON: EL NOMBRE DEL CLIENTE, CODIGO DE LA HERRAMIENTA, LA CANTIDAD SOLICITADA Y EL 
NUMERO DE LA SOLICITUD.
*/

