/*
-------------------------------
-------- PRACTICO 9  ----------
-------------------------------*/
USE VENTAS;
/*
8. TRANSACCION QUE REGISTRE UNA SOLICITUD, REGISTRE LA VENTA RESPECTIVA Y ACTUALICE EL ALMACEN.
LOS DATOS SON: EL NOMBRE DEL CLIENTE, CODIGO DE LA HERRAMIENTA, LA CANTIDAD SOLICITADA Y EL 
NUMERO DE LA SOLICITUD.
*/

DELIMITER //
CREATE PROCEDURE TRANSACCION8(IN NOMBCLI VARCHAR(35), IN CODH CHAR(6),
 IN CANTS SMALLINT, IN NSO SMALLINT )
 BEGIN
	DECLARE CODCLI CHAR(11);
    DECLARE PRE DECIMAL(6,2);
    IF EXISTS(SELECT * FROM CLIENTE WHERE NOMBRE = NOMBCLI)THEN
		IF EXISTS(SELECT * FROM HERRAMIENTA WHERE COD = CODH) THEN
			SELECT CI INTO CODCLI FROM CLIENTE WHERE NOMBRE = NOMBCLI;
            SELECT PRECIO INTO PRE FROM HERRAMIENTA WHERE COD = CODH;
            
            INSERT INTO SOLICITUD VALUES(NSO, NOW(), CANTS, CODCLI, CODH, ' ');
            
            INSERT INTO VENTA VALUES(CODH, CODCLI, NSO, CANTS, CANTS*PRE);
            
            UPDATE ALMACEN SET CEGRESO = CEGRESO + CANTS, CSALDO= CSALDO - CANTS WHERE COD = CODH;
            
            IF (MYSQL_ERRNO <> 0) THEN
				BEGIN
				ROLLBACK;
				SIGNAL SQLSTATE '45000'
				SET MESSAGE_TEXT= 'TRANSACCIÓN NO COMPLETADA', MYSQL_ERRNO = '1006'; 
				END;
				END IF;
        ELSE SELECT 'LA HERRAMIENATA NO EXISTE'; END IF;
    ELSE SELECT 'EL CLIENTE NO EXISTE'; END IF;
 END//
DELIMITER ;

CALL TRANSACCION8('CARLOS RUIZ','H-0001', 20, 3);
CALL TRANSACCION8('CARLOS RUIZ','H-0001', 7, 4);

SELECT * FROM CLIENTE;
SELECT * FROM ALMACEN;
SELECT * FROM SOLICITUD;
SELECT * FROM VENTA;
