/*
-------------------------------
-------- PRACTICO 9  ----------
-------------------------------*/
USE VENTAS;
/*
8. TRANSACCION QUE REGISTRE UNA SOLICITUD, REGISTRE LA VENTA RESPECTIVA Y ACTUALICE EL ALMACEN.
LOS DATOS SON: EL NOMBRE DEL CLIENTE, CODIGO DE LA HERRAMIENTA, LA CANTIDAD SOLICITADA Y EL 
NUMERO DE LA SOLICITUD.
*/

DELIMITER //
CREATE PROCEDURE TRANSACCION8(IN NOMBCLI VARCHAR(35), IN CODH CHAR(6),
 IN CANTS SMALLINT, IN NSO SMALLINT )
 BEGIN
	DECLARE CODCLI CHAR(11);
    DECLARE PRE DECIMAL(6,2);
    IF EXISTS(SELECT * FROM CLIENTE WHERE NOMBRE = NOMBCLI)THEN
		IF EXISTS(SELECT * FROM HERRAMIENTA WHERE COD = CODH) THEN
            IF NOT EXISTS (SELECT * FROM VENTA WHERE COD = CODH AND NSOL = NSO) THEN
            
            SELECT CI INTO CODCLI FROM CLIENTE WHERE NOMBRE = NOMBCLI;
            SELECT PRECIO INTO PRE FROM HERRAMIENTA WHERE COD = CODH;
             IF((SELECT CSALDO FROM ALMACEN WHERE COD = CODH) > CANTS) THEN
             BEGIN
				INSERT INTO SOLICITUD VALUES(NSO, NOW(), CANTS, CODCLI, CODH, ' ');
            
				INSERT INTO VENTA VALUES(CODH, CODCLI, NSO, CANTS, CANTS*PRE);
            
				UPDATE ALMACEN SET CEGRESO = CEGRESO + CANTS, CSALDO= CSALDO - CANTS WHERE COD = CODH;
			END;
            ELSE 
            BEGIN
            ROLLBACK;
            SELECT 'LA CANTIDAD SOLICITADA ES MAYOR AL SALDO EN ALMACEN' AS MENSAJE;
            END;END IF;
            
            IF (MYSQL_ERRNO <> 0) THEN
				BEGIN
				ROLLBACK;
				SIGNAL SQLSTATE '45000'
				SET MESSAGE_TEXT= 'TRANSACCIÓN NO COMPLETADA', MYSQL_ERRNO = '1006'; 
				END;
				END IF;
                
            ELSE SELECT 'LA VENTA YA EXISTE' AS MENSAJE; END IF;
        ELSE SELECT 'LA HERRAMIENATA NO EXISTE' AS MENSAJE; END IF;
    ELSE SELECT 'EL CLIENTE NO EXISTE'AS MENSAJE; END IF;
 END//
DELIMITER ;

CALL TRANSACCION8('CARLOS RUIZ','H-0001', 5, 3);


/*9. TRANSACCION QUE REGISTRE LA SOLICITUD REALIZADA POR UN CLIENTE DE UNA HERRAMIENTA POR UNA 
CANTIDAD DETERMINADA SI LA CANTIDAD NECESARIA ESTA DISPONIBLE EN EL ALMACEN (EL SALDO CUBRE 
LA CANTIDAD SOLICITADA), CASO CONTRARIO SOLAMENTE SE REGISTRE LA SOLICITUD CON LA CANTIDAD 
EXISTENTE EN EN ALMACEN. LOS DATOS SON: EL NOMBRE DEL CLIENTE, LA DESCRIPCION DE LA 
HERRAMIENTA Y LA CANTIDAD SOLICITADA */

DELIMITER //
CREATE PROCEDURE TRANSACCION9 (IN NOMB VARCHAR(35), IN DES VARCHAR(35), IN CANTS SMALLINT)
BEGIN
	IF EXISTS(SELECT * FROM CLIENTE WHERE NOMBRE = NOMB)THEN
		IF EXISTS (SELECT * FROM HERRAMIENTA WHERE DESCRIPCION = DES)THEN
        BEGIN
			DECLARE CODC CHAR(11); DECLARE CODH CHAR(6);
            DECLARE NSO SMALLINT; DECLARE CANTE SMALLINT;
            
            SELECT CI INTO CODC FROM CLIENTE WHERE NOMBRE = NOMB;
            SELECT COD INTO CODH FROM HERRAMIENTA WHERE DESCRIPCION = DES;
            SELECT MAX(NSOL) + 1 INTO NSO FROM SOLICITUD;
            SELECT CSALDO INTO CANTE FROM ALMACEN WHERE COD = CODH;
            
            IF( CANTE > CANTS) THEN
				INSERT INTO SOLICITUD VALUES(NSO, NOW(), CANTS, CODC, CODH, '');
            ELSE
				INSERT INTO SOLICITUD VALUES(NSO, NOW(), CANTE, CODC, CODH, '');
            END IF;
				IF (MYSQL_ERRNO <> 0) THEN
					BEGIN
					ROLLBACK;
					SIGNAL SQLSTATE '45000'
					SET MESSAGE_TEXT= 'TRANSACCIÓN NO COMPLETADA', MYSQL_ERRNO = '1006'; 
					END;
				END IF;
         END;   
        ELSE SELECT 'LA HERRAMIENTA NO EXISTE' AS MENSAJE; END IF;
    ELSE SELECT 'EL CLIENTE NO EXISTE' AS MENSAJE;END IF;
END//
DELIMITER ;

CALL TRANSACCION9('CARLOS RUIZ', 'ALICATE', 60);

/*10. TRANSACCION QUE ELIMINE EL REGISTRO DE LA COMPRA DE HERRAMIENTAS DE UN DETERMINADO 
COMERCIAL REGISTRADO EN LA BASE DE DATOS. ASI MISMO ACTUALICE EL ALMACEN DE MANERA QUE SE 
CONTABILICE LA CANTIDAD COMPRADA. LOS DATOS SON: EL CODIGO DE LA HERRAMIENTA Y NOMBRE DEL 
COMERCIAL EN EL QUE SE REALIZO LA COMPRA*/

DELIMITER //
CREATE PROCEDURE TRANSACCION10(IN CODH CHAR(6),IN NOMBC VARCHAR(35))
BEGIN
	IF EXISTS( SELECT * FROM HERRAMIENTA WHERE COD = CODH) THEN
		IF EXISTS (SELECT * FROM COMERCIAL WHERE NOMBRE = NOMBC) THEN
        BEGIN
			DECLARE NITC CHAR (11);
            DECLARE CANT SMALLINT;
            SELECT NIT INTO NITC FROM COMERCIAL WHERE NOMBRE = NOMBC;
            SELECT CANTIDADC INTO CANT FROM COMPRA WHERE COD = CODH AND NIT = NITC;
            
            IF EXISTS ( SELECT * FROM COMPRA WHERE COD = CODH AND NIT = NITC )THEN
            BEGIN
				DELETE FROM COMPRA WHERE NIT = NITC AND COD = CODH;
                UPDATE ALMACEN SET CINGRESO = CINGRESO + CANT, CSALDO = CINGRESO - CEGRESO WHERE COD = CODH;
			END;
            ELSE
            BEGIN
				ROLLBACK;
				SELECT 'LA COMPRA DEL ARTICULO NO ESTA REGISTRADO' AS MENSAJE;
            END; END IF;
            IF (MYSQL_ERRNO <> 0) THEN
					BEGIN
					ROLLBACK;
					SIGNAL SQLSTATE '45000'
					SET MESSAGE_TEXT= 'TRANSACCIÓN NO COMPLETADA', MYSQL_ERRNO = '1006'; 
					END;
				END IF;
		END;
        ELSE SELECT 'EL COMERCIAL NO ESTA REGISTRADO' AS MENSAJE;END IF;
    ELSE SELECT 'LA HERRAMIENTA NO ESTA REGISTRADA' AS MENSAJE;END IF;
END//
DELIMITER ;

CALL TRANSACCION10('H-0001', 'LIMPOR LTDA.');

/*11. TRANSACCION QUE ACTUALICE LA DISMINUCION EN LA CANTIDAD DE UNA VENTA CORRESPONDIENTE A UNA 
SOLICITUD. SE DEBERA ACTUALIZAR TAMBIEN LA CANTIDAD DE LA SOLICITUD CORRESPONDIENTE Y SU 
ACTUALIZACION EN EL ALMACEN. LOS DATOS SON: EL NUMERO DE LA SOLICITUD Y CANTIDAD EN LA QUE SE 
DISMINUYE LA VENTA.*/

DELIMITER //
CREATE PROCEDURE TRANSACCION11(IN NSO SMALLINT, IN CANTD SMALLINT)
BEGIN
IF EXISTS (SELECT * FROM SOLICITUD WHERE NSOL = NSO) THEN
	IF EXISTS(SELECT * FROM VENTA WHERE NSOL = NSO)THEN
		BEGIN
        DECLARE CODH CHAR(6);
        SELECT COD INTO CODH FROM VENTA WHERE NSOL = NSO;
        
        UPDATE VENTA SET CANTIDAD = CANTIDAD - CANTD WHERE NSOL = NSO;
        UPDATE SOLICITUD SET CANTIDAD = CANTIDAD - CANTD WHERE NSOL = NSO;
        UPDATE ALMACEN SET CEGRESO = CEGRESO - CANTD, CSALDO = CSALDO + CANTD WHERE COD = CODH;
        END;
        
         IF (MYSQL_ERRNO <> 0) THEN
					BEGIN
					ROLLBACK;
					SIGNAL SQLSTATE '45000'
					SET MESSAGE_TEXT= 'TRANSACCIÓN NO COMPLETADA', MYSQL_ERRNO = '1006'; 
					END;
				END IF;
        
    ELSE SELECT 'NO EXISTE VENTA REGISTRADA' AS MENSAJE; END IF;
ELSE SELECT 'NO EXISTE SOLICITUD REGISTRADA' AS MENSAJE; END IF;
END//
DELIMITER ;

CALL TRANSACCION11(3,2);





