/*
-------------------------------
-------- PRACTICO 11  ----------
-------------------------------*/

USE ENTREGAS;

ALTER TABLE TECNICO ADD COLUMN ITEM CHAR(5);
ALTER TABLE TECNICO ADD COLUMN TELEFONO INT;

/* 13. VALIDAR EN LA TABLA ENTREGA QUE EL NUMERO DE ENTREGA SEA POSITIVO Y NO TENGA MAS DE 5 
DIGITOS. */

ALTER TABLE ENTREGA ADD
CONSTRAINT EJERCICIO13 CHECK(NE > 0 AND NE < 100000);

/*14. VALIDAR EN LA TABLA ENTREGA QUE LA FECHA SEA IGUAL A LA FECHA ACTUAL (2022).*/

ALTER TABLE ENTREGA ADD
CONSTRAINT EJERICIO14 CHECK (YEAR(FECHA)= 2023);

/*15. EL CI DEL TECNICO PARA 11 CARACTERES (TIPO CADENA). POR EJ. 1082397 CH.*/

ALTER TABLE TECNICO ADD
CONSTRAINT EJERCICIO15 CHECK(CI REGEXP '[0-9]{8}-[A-Z]{2}');

/*16. VALIDE LA FECHA DE ENTREGA PARA 30 DIAS PARA CADA MES Y 12 MESES.*/

ALTER TABLE ENTREGA ADD
CONSTRAINT EJERCICIO16 CHECK (DAY(FECHA) BETWEEN 1 AND 30 AND MONTH(FECHA) BETWEEN 1 AND 12);

/*17. LA FECHA DE ENTREGA AL TECNICO SOLO PARA LOS DIAS IMPARES DE CADA MES (UTILIZAR MOD).*/
ALTER TABLE ENTREGA ADD
CONSTRAINT EJERCICIO17 CHECK(MOD(DAY(FECHA), 2) = 1);

/*18. VERIFICAR QUE EL CODIGO DE LA HERRAMIENTA TENGA EL FORMATO: H-XXXX, DONDE LA X PUEDE SER 
CUALQUIER DIGITO NUMERICO (0,1,2,….., 9)*/

ALTER TABLE HERRAMIENTA ADD
CONSTRAINT EJERCICIO18 CHECK(CODIGO REGEXP 'H-[0-9]{4}');

