/*
5.- SE TIENEN EL SIGUIENTE MODELO LOGICO GLOBAL DE DATOS (MLD)
 MAQUINA ( CODIGO, Descripción, Unidad, Precio )
 GARAGE ( CODIGO, CIngreso, CEgreso, CSaldo )
 DISTRIBUIDOR ( NIT, Nombre, Direccion, Celular )
USUARIO ( CI, Nombre, Edad, Sexo, Telefono )
 PEDIDO ( NPED, FechasP CantidadP, CI , CODIGO )
 VENTA ( CODIGO, CI, FechaV, CantidadV )
 COMPRA ( CODIGO , NIT , FechaC, CantidadC )
 
A. CREAR LA BASE DE DATOS BDMAQUINAS.

B. CREAR LAS TABLAS Y RELACIONES.
RESTRICIONES:
• FECHAS POR DEFECTO CON LAS DEL SISTEMA, 
• NUMERO DE PEDIDO AUTONUMERICO A PARTIR DEL 1000 CON INCREMENTO DE 1, 
• PRECIO PARA VALORES POSITIVOS, 
• CANTIDADES PARA VALORES SOLO DE 2 DIGITOS, 
• EDAD EN EL RANGO DE 21 A 65 AÑOS, 
• SEXO PARA VALORES F Y M
*/

CREATE DATABASE BDMAQUINAS
	CHAR SET utf8mb4 COLLATE utf8mb4_general_ci;
    
USE BDMAQUINAS;

CREATE TABLE MAQUINA (
	CODIGO CHAR(10) NOT NULL PRIMARY KEY,
	DESCRIPCION VARCHAR(100) DEFAULT '',
	UNIDAD INT NOT NULL, CHECK (UNIDAD > 0),
	PRECIO FLOAT DEFAULT 0.0, CHECK(PRECIO > 0)
) ENGINE InnoDB;

CREATE TABLE GARAGE (
	CODIGO CHAR(10) NOT NULL,
	CINGRESO FLOAT NOT NULL, CHECK(CINGRESO > 0),
	CEGRESO FLOAT NOT NULL, CHECK(CEGRESO > 0),
	CSALDO FLOAT NOT NULL, CHECK(CSALDO > 0),
	FOREIGN KEY (CODIGO) REFERENCES MAQUINA(CODIGO)
)ENGINE InnoDB;

CREATE TABLE DISTRIBUIDOR (
	NIT INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(35) NOT NULL,
	DIRECCION VARCHAR(50) DEFAULT '',
	CELULAR INT NOT NULL
)ENGINE InnoDB;

CREATE TABLE USUARIO (
	CI CHAR (11) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(35) NOT NULL,
	EDAD INT NOT NULL, CHECK(EDAD >= 21 AND EDAD <=65),
	SEXO CHAR(1), CHECK(SEXO='F' OR SEXO='M'),
	TELEFONO INT NOT NULL
) ENGINE InnoDB;

CREATE TABLE PEDIDO(
	NPED INT PRIMARY KEY AUTO_INCREMENT,
	FECHAP DATETIME DEFAULT NOW(),
	CANTIDADP TINYINT NOT NULL, CHECK(CANTIDADP BETWEEN 10 AND 99),
	CI CHAR(11) NOT NULL,
	CODIGO CHAR(10) NOT NULL,
	FOREIGN KEY (CI) REFERENCES USUARIO(CI),
	FOREIGN KEY (CODIGO) REFERENCES MAQUINA(CODIGO)
)ENGINE InnoDB AUTO_INCREMENT=1000;

CREATE TABLE VENTA (
	CODIGO CHAR(10) NOT NULL,
	CI CHAR(11) NOT NULL,
	FECHAV DATETIME DEFAULT NOW(),
	CANTIDADV TINYINT, CHECK(CANTIDADV BETWEEN 10 AND 99),
	PRIMARY KEY(CODIGO, CI),
	FOREIGN KEY(CODIGO) REFERENCES MAQUINA(CODIGO),
	FOREIGN KEY(CI) REFERENCES USUARIO(CI)
)ENGINE InnoDB;

CREATE TABLE COMPRA (
	CODIGO CHAR(10) NOT NULL,
	NIT INT NOT NULL,
	FECHAC DATETIME DEFAULT NOW(),
	CANTIDADC TINYINT, CHECK(CANTIDADC BETWEEN 10 AND 99),
	PRIMARY KEY(CODIGO, NIT),
	FOREIGN KEY(CODIGO) REFERENCES MAQUINA(CODIGO),
	FOREIGN KEY(NIT) REFERENCES DISTRIBUIDOR(NIT)
)ENGINE InnoDB;

















