/*
6.- DADO EL SIGUIENTE MODELO LOGICO GLOBAL DE DATOS (MLD)


VEHICULO ( NPLACA, MARCA, MODELO, CILINDRADA, COLOR )
VAGONETA ( NPLACA, NPUERTAS, NMOTOR )
 CAMONETA ( NPLACA, CAPACIDAD, TRACCION )
 PROPIETARIO ( NIT, NOMBRE, DIRECCION )
 CLIENTE ( CI, NOMBRE, TELEFONO, CATEGORIA )
 ALQUILER ( NPLACA, CI, NIT, FECHA, COSTOSF, COSTOCF ) 
COMPARTE ( CI, CIR, PORCENTAJE)


A. CREAR LA BASE DE DATOS BDALQUILER.
B. CREAR LAS TABLAS Y RELACIONES.
RESTRICCIONES:
• EL COSTO SIN FACTURA (COSTOSF) MENOR QUE EL COSTO CON FACTURA (COSTOCF); 
• NUMERO DE PUERTAS PARA VALORES POSITIVOS DE UN DIGITO, 
• FECHA POR DEFECTO CON LA DEL SISTEMA, 
• TRACCION, PARA D (DELANTERA), T (TRACERA), H (DOBLE TRACCION)
• MARCA PARA: TOYOTA, NISSAN, SUZUKI Y CHEVROLET
• PORCENTAJE VALOR POSITIVO HASTA 100
• CATEGORIA P, A, B, C PARA LOS CLIENTES.
*/


CREATE DATABASE BDALQUILER
	CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE BDALQUILER;

CREATE TABLE VEHICULO (
NPLACA CHAR(7) NOT NULL PRIMARY KEY,
MARCA ENUM('TOYOTA','NISSAN', 'SUZUKI', 'CHEVROLET'),
MODELO INT NOT NULL,
CILINDRADA INT NOT NULL,
COLOR VARCHAR(20) NOT NULL
)ENGINE InnoDB;


CREATE TABLE VAGONETA (
	NPLACA CHAR(7) NOT NULL,
    NPUERTAS TINYINT NOT NULL, CHECK(NPUERTAS BETWEEN 1 AND 9),
    NMOTOR INT NOT NULL,
	PRIMARY KEY(NPLACA),
    FOREIGN KEY (NPLACA) REFERENCES VEHICULO (NPLACA)
) ENGINE InnoDB;

CREATE TABLE CAMIONETA (
	NPLACA CHAR(7) NOT NULL,
	CAPACIDAD TINYINT NOT NULL, CHECK(CAPACIDAD > 0),
	TRACCION ENUM('D', 'T', 'H'),
	PRIMARY KEY(NPLACA),
	FOREIGN KEY (NPLACA) REFERENCES VEHICULO (NPLACA)
) ENGINE InnoDB;

CREATE TABLE PROPIETARIO(
	NIT INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(35) NOT NULL,
	DIRECCIONE VARCHAR (40) DEFAULT ''
) ENGINE InnoDB;

CREATE TABLE CLIENTE (
	CI CHAR(11) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(35) NOT NULL,
    TELEFONO INT NOT NULL,
    CATEGORIA ENUM('P', 'A', 'B', 'C')
) ENGINE InnoDB;

CREATE TABLE ALQUILER (
	NPLACA  CHAR(7) NOT NULL,
    CI CHAR(11) NOT NULL,
    NIT INT NOT NULL,
    FECHA DATETIME DEFAULT NOW(),
    COSTOSF FLOAT DEFAULT 0.0, CHECK(COSTOSF > 0),
	COSTOCF FLOAT DEFAULT 0.0, CHECK(COSTOCF > 0), CHECK( COSTOSF < COSTOCF),
    PRIMARY KEY(NPLACA, CI, NIT),
    FOREIGN KEY (NPLACA) REFERENCES VEHICULO(NPLACA),
    FOREIGN KEY (CI) REFERENCES CLIENTE(CI),
    FOREIGN KEY (NIT) REFERENCES PROPIETARIO(NIT)
) ENGINE InnoDB;

CREATE TABLE COMPARTE (
	CI CHAR(11) NOT NULL,
    CIR CHAR(11) NOT NULL,
    PORCENTAJE TINYINT, CHECK(PORCENTAJE >=0 AND PORCENTAJE <=100),
    PRIMARY KEY(CI, CIR),
    FOREIGN KEY (CI) REFERENCES CLIENTE(CI),
    FOREIGN KEY (CIR) REFERENCES CLIENTE(CI)
) ENGINE InnoDB;

-- ---------------------------

-- 7.-REALIZAR LAS SIGUIENTES CONSULTAS EN SQL.


-- A. INSERTAR EL REGISTRO DE UN VEHCULO TOYOTA BLANCO. MODELO 2010, 1600 CC, PLACA 2160KN

INSERT INTO VEHICULO VALUES ('JKL-216','TOYOTA', 2010, 1600, 'blanco');


-- B. ELIMINAR LOS REGISTROS DE VEHICULOS CUYO MODELO ES INFERIOR A 200 DE COLOR NEGRO.

DELETE FROM VEHICULO WHERE MODELO < 2000 AND COLOR = 'NEGRO';


-- C. ACTUALIZAR LOS REGISTROS DE LOS CLIENTES CATEGORIA P MAYORES DE 40 AÑOS A CATEGORIA A.

UPDATE CLIENTE SET CATEGORIA = 'A' WHERE CATEGORIA = 'P'; -- no hay campo edad en la tabla cliente

/* D. REALIZAR LA UNION RELACIONAL DE LAS TABLAS ALQUILER, VEHICULO, PROPIETARIO Y CLIENTE, QUE 
MUESTRE MARCA DEL VEHICULO, NOMBRES DEL PROPIETARIO Y CLIENTE Y LA FECHA DEL ALQUILER. */

SELECT V.MARCA, P.NOMBRE AS 'PROPIETARIO', C.NOMBRE AS 'CLIENTE', A.FECHA
FROM ALQUILER A INNER JOIN VEHICULO V ON A.NPLACA = V.NPLACA
INNER JOIN PROPIETARIO P ON A.NIT =  P.NIT
INNER JOIN CLIENTE C ON A.CI = C.CI;

/* E. MOSTRAR UNA LISTA DE CUANTOS VEHICULO TIENE CADA COLOR, CUYO MODELO ESTA COMPRENDIDA 
ENTRE EL AÑO 2000 Y 2010. UTILIZAR LA FUNCION CONTAR. */

SELECT COLOR , COUNT(*) AS 'CANTIDAD' FROM VEHICULO
WHERE MODELO BETWEEN 2000 AND 2010
GROUP BY COLOR;

