/*
-------------------------------
----   TRABAJO PRACTICO 7  ----
-------------------------------

NOMBRE: JUEL VARGAS ROJAS
GRUPO: 1
*/

USE ENTREGAS;

-- --1
DELIMITER //
CREATE FUNCTION EJERCICIO11(CANT INT) RETURNS FLOAT
READS SQL DATA DETERMINISTIC
BEGIN
	DECLARE PMIN FLOAT;
    SELECT MIN(H.PRECIO) INTO PMIN FROM HERRAMIENTA H 
    INNER JOIN ALMACEN A ON H.CODIGO = H.CODIGO
    WHERE A.CSALDO = CANT;
	RETURN PMIN;
END //
DELIMITER ;

SELECT EJERCICIO11(20) AS 'PRECIO MAS BAJO';
SELECT * FROM ALMACEN;

-- --2

DELIMITER //
CREATE FUNCTION EJERCICIO12(AN INT) RETURNS INT
READS SQL DATA DETERMINISTIC
BEGIN
	DECLARE DIF INT;
    SELECT MAX(NE) - MIN(NE) INTO DIF FROM ENTREGA 
    WHERE YEAR(FECHA) = AN;
    RETURN DIF;
END// 
DELIMITER ;

SELECT EJERCICIO12(2023) AS 'DIFERENCIA ENTREGA';

SELECT * FROM ENTREGA;

-- ----3

DELIMITER //
CREATE FUNCTION EJERCICIO13( AN INT , MES INT) RETURNS INT
READS SQL DATA DETERMINISTIC
BEGIN
	DECLARE NUE INT;
    SELECT COUNT(NE) INTO NUE FROM ENTREGA 
    WHERE YEAR(FECHA) = AN AND MONTH(FECHA) = MES;
    
    RETURN NUE;
END//
DELIMITER ;

SELECT EJERCICIO13(2023, 5) AS 'CANTIDAD ENTREGAS';
