/*
-------------------------------
-------- PRACTICO 9  ----------
-------------------------------*/
USE ENTREGAS; 

CREATE TABLE TECNICO (
CI CHAR(11) NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(35) DEFAULT ' ',
DIRECCION VARCHAR(30) DEFAULT ' ',
SEXO CHAR(1), CHECK(SEXO IN('F', 'M')),
EDAD SMALLINT DEFAULT 0
) ENGINE = InnoDB;

INSERT INTO TECNICO VALUES ('10545678', 'JULIO CASTRO', 'CALLE SANTA LUCIA # 17', 'M', 25), 
 ('10541123', 'MARIA RUIZ', 'CALLE SANTA LUCIA # 21', 'F', 19), 
 ('10677678', 'JUAN PEMINTEL', 'CALLE SANTA LUCIA # 30', 'M', 40), 
 ('10356781', 'CARLA ORTIZ', ' ', 'F', 20);
 
ALTER TABLE ENTREGA ADD COLUMN CI CHAR(11);
UPDATE ENTREGA SET CI = 10356781 WHERE NE=1001;
UPDATE ENTREGA SET CI = 10356781 WHERE NE=1002;
UPDATE ENTREGA SET CI = 10356781 WHERE NE=1003;


/*13. VISTA QUE MUESTRE LA HERRAMIENTA QUE MENOS SE HA ENTREGADO, MOSTRANDO SU CODIGO, 
DESCRIPCION Y CANTIDAD ENTREGADA.*/

CREATE VIEW EJERCICIO13
AS 
	SELECT H.CODIGO AS 'CODIGO',
			H.DESCRIPCION AS 'HERRAMIENTA',
            E.CANTIDAD AS 'CANTIDAD ENTREGADA'
	FROM HERRAMIENTA H INNER JOIN ENTREGA E ON E.CODIGO = H.CODIGO
    WHERE E.CANTIDAD = (SELECT MIN(CANTIDAD) FROM ENTREGA) LIMIT 1;
    
SELECT * FROM EJERCICIO13;


            
    