/*
-------------------------------
---------  PRACTICO 6  --------
-------------------------------
*/

/* PRACTICO DONDE SE REALIZAN PROCEDIMIENTOS ALMACENADOS DE CONSULTA */
USE ENTREGAS;

/* 1. P.A. QUE MUESTRE UNA LISTA DE HERRAMIENTAS CUYO 
PRECIO ESTA ENTRE 10 Y 20 Bs. */
DELIMITER //
	CREATE PROCEDURE PAC_EJERCICIO1()
    BEGIN
		SELECT * FROM HERRAMIENTA WHERE PRECIO BETWEEN 10 AND 20;
    END//
DELIMITER ;

CALL PAC_EJERCICIO1;

/* 2. P.A. QUE MUESTRE UNA LISTA DE HERRAMIENTAS CUYA DESCRIPCION COMIENZA CON LA LETRA " A " */
DELIMITER //
	CREATE PROCEDURE PAC_EJERCICIO2()
    BEGIN
		SELECT * FROM HERRAMIENTA WHERE DESCRIPCION LIKE 'A%';
    END//
DELIMITER ;

CALL PAC_EJERCICIO2;

/* 3. P.A. QUE MUESTRE LAS CANTIDADES PROMEDIO DE ENTREGAS REALIZADAS 
 DE CADA HERRAMIENTA, CORRESPONDIENTES A SEPTIEMBRE DEL AÑO 2018 */
 
 DELIMITER //
	CREATE PROCEDURE PAC_EJERCICIO3()
	BEGIN
		SELECT H.DESCRIPCION AS 'HERRAMIENTA', AVG(E.CANTIDAD) AS 'PROMEDIO ENTREGA'
        FROM ENTREGA E INNER JOIN HERRAMIENTA H ON H.CODIGO = E.CODIGO
        WHERE YEAR(FECHA) = 2018 AND MONTH(9)
        GROUP BY H.DESCRIPCION;
    END//
 DELIMITER ;
 
 CALL PAC_EJERCICIO3;
 
 /*4. P.A. QUE MUESTRE LAS CANTIDADES TOTALES ENTREGADAS PARA CADA HERRAMIENTA CUYO PRECIO ES AL 
MENOS 10 Bs.*/
DELIMITER //
	CREATE PROCEDURE PAC_EJERCICIO4()
    BEGIN
		SELECT H.DESCRIPCION AS 'HERRAMIENTA', SUM(E.CANTIDAD) AS 'CANTIDAD TOTAL ENTREGADA'
        FROM HERRAMIENTA H INNER JOIN ENTREGA E 
        ON H.CODIGO = E.CODIGO
        WHERE H.PRECIO >= 10
        GROUP BY E.CODIGO;
    END//
DELIMITER ;

CALL PAC_EJERCICIO4;

/* 17. P.A. QUE MUESTRE LAS HERRAMIENTAS Y SUS PROMEDIOS DE CANTIDADES ENTREGADAS 
CORRESPONDIENTE A LA PRIMERA QUINCENA DE MAYO DEL 2018 */

DELIMITER //
	CREATE PROCEDURE PA_EJERCICIO17()
    BEGIN
		SELECT H.DESCRIPCION AS 'HERRAMIENTA', AVG(E.CANTIDAD) AS 'PROMEDIO ENTREGADO'
        FROM HERRAMIENTA H INNER JOIN ENTREGA E ON E.CODIGO = H.CODIGO
        WHERE E.FECHA BETWEEN '2018-05-01' AND '2018-05-15'
        GROUP BY H.DESCRIPCION;
    END //
DELIMITER ;

CALL PA_EJERCICIO17;


/* 18. P.A. QUE MUESTRE EL PORCENTAJE DE CANTIDADES TOTALES ENTREGADAS EL PRIMER TRIMESTRE DEL 
AÑO ACTUAL EN CURSO (DEL SISTEMA), CON RESPECTO A LA CANTIDAD DE ENTRADA EN EL ALMACEN PARA 
CADA HERRAMIENTA */

DELIMITER //
	CREATE PROCEDURE PA_EJERCICIO18()
    BEGIN
		SELECT 
			H.DESCRIPCION AS 'HERRAMIENTA', A.CENTRADA 'CANTIDAD ENTRADA',
			(SUM(E.CANTIDAD)/A.CENTRADA) * 100 AS 'PORCENTAJE'
		FROM
			HERRAMIENTA H INNER JOIN ENTREGA E ON E.CODIGO = H.CODIGO
			INNER JOIN ALMACEN A ON H.CODIGO = A.CODIGO
		WHERE
			E.FECHA BETWEEN CONCAT(YEAR(NOW()),'-01-01') 
				AND CONCAT(YEAR(NOW()), '-03-31')
			GROUP BY H.CODIGO
			ORDER BY PORCENTAJE ASC;
    END //
DELIMITER ;

CALL PA_EJERCICIO18;


/* 19. P.A. QUE MUESTRE PARA CADA HERRAMIENTA LA CANTIDAD DE HERRAMIENTAS ENTREGADAS. CUYA 
CANTIDAD ESTE COMPRENIDIDA ENTRE MAS Y MENOS 5 UNIDADES LA CANTIDAD PROMEDIO GENERAL.*/

DELIMITER //
		CREATE PROCEDURE PA_EJERCICIO19()
	BEGIN
		DECLARE CPROM INT;
        
		SELECT AVG(CANTIDAD) INTO CPROM FROM ENTREGA;
		
		SELECT H.CODIGO, H.DESCRIPCION, COUNT(*) AS CANTIDAD_ENTREGAS
		FROM HERRAMIENTA H
		INNER JOIN ENTREGA E ON H.CODIGO = E.CODIGO
		WHERE E.CANTIDAD BETWEEN CPROM - 5 AND CPROM + 5
		GROUP BY H.CODIGO, H.DESCRIPCION;
	END //
DELIMITER ;
CALL PA_EJERCICIO19;

/*20. P.A. QUE MUESTRE EL NUMERO DE ENTREGAS REALIZADAS PARA CADA HERRAMIETA, PARA ENTREGAS 
CUYO COSTO ESTA 10% POR ENCIMA DEL COSTO MINIMO GENERAL. SOLAMENTE SE DEBEN MOSTRAR LAS 
HERRAMIENTAS CUYO NUMERO DE ENTREGAS SEA SUPERIOR A 5 */

DELIMITER //
CREATE PROCEDURE PA_EJERCICIO20()
BEGIN
    DECLARE C_MIN FLOAT;
    SELECT MIN(PRECIO) INTO C_MIN FROM HERRAMIENTA;
    SELECT H.DESCRIPCION AS 'HERRAMIENTA', COUNT(*) AS 'NUMERO_ENTREGAS', E.CODIGO
    FROM ENTREGA E INNER JOIN HERRAMIENTA H ON E.CODIGO = H.CODIGO
    WHERE E.CODIGO IN (
        SELECT CODIGO 
        FROM HERRAMIENTA 
        WHERE PRECIO >= C_MIN * 1.1
    )
    GROUP BY E.CODIGO
    HAVING NUMERO_ENTREGAS > 5;
END //
DELIMITER ;

CALL PA_EJERCICIO20;
